const webpack = require('webpack');
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// Utils
const path = require('path');
const glob = require('glob');

/**
 * Get entries for all files in a directory
 *
 * @param {String} in_dir -  Input directory to get entries for
 * @param {String} [out_dir] - Optional output directory for entries
 * @param {Object} [settings] - Settings for processing entries
 * @param {String} [settings.extension] - Optionally, only match files with given extension
 * @param {boolean} [settings.skip_partial] - Skip file names starting with `_`. Defaults to `true`
 */
const getDirEntries = (in_dir, out_dir, { extension, skip_partial }) => {
	// Default skip_partial to true
	skip_partial = skip_partial === undefined ? true : skip_partial;

	// Create search pattern
	const pattern = path.resolve(
		process.cwd(),
		in_dir,
		extension !== undefined ? `*.${extension}` : '*'
	);
	// Get entries for search pattern
	return glob.sync(pattern).reduce((acc, file_path) => {
		// Get file info
		const file_ext = path.extname(file_path);
		const file_name = path.basename(file_path, file_ext);

		// Skip partials
		if (skip_partial && file_name.slice(0, 1) === '_') {
			return acc;
		}

		// Create entry output path
		const out_path =
			out_dir !== undefined
				? `${out_dir}/${file_name}`
				: `css/blocks/${file_name}`;

		// Add entry
		acc[out_path] = file_path;
		return acc;
	}, {});
};

// Extend wordpress default webpack config
/** @type {webpack.Configuration} */
module.exports = {
	...defaultConfig,
	// Set custom entry points for js and scss
	entry: {
		// Include wordpress default entries
		...defaultConfig.entry(),

		'js/main': path.resolve(process.cwd(), 'src', 'main.js'),
		'js/editor': path.resolve(process.cwd(), 'src', 'editor.js'),
		'css/main': path.resolve(process.cwd(), 'src/scss', 'main.scss'),
		'css/editor': path.resolve(process.cwd(), 'src/scss', 'editor.scss'),
		// Get entries for core block styles
		...getDirEntries('src/scss/blocks/core', 'css/blocks/core', {
			extension: 'scss',
		}),
		// Get entries for windmill block styles
		...getDirEntries(
			'src/scss/blocks/windmill-blocks',
			'css/blocks/windmill-blocks',
			{ extension: 'scss' }
		),
	},
	resolve: {
		...defaultConfig.resolve,
		alias: {
			'@': path.resolve(__dirname, './src'),
		},
	},
	// Add webpack plugins
	plugins: [
		// Include wordpress default plugins
		...defaultConfig.plugins,

		// Remove empty '*.js' files generated by webpack
		new RemoveEmptyScriptsPlugin({
			// Run after wordpress `*.asset.php` files have been generated
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		}),
	],
};
