<?php
/**
 * Generate plugin global styles
 *
 * @package WindmillBlocks;
 */

namespace WindmillBlocks\StyleGeneration;

use WP_Error;

/**
 * Add inline plugin global stylesheet to page head
 */
function inline_plugin_global_styles() {
	// Load global stylesheet.
	$stylesheet_path = get_global_stylesheet();
	$stylesheet_data = file_get_contents( WINDMILL_BLOCKS_PLUGIN_DIR . $stylesheet_path );

	if ( false === $stylesheet_data ) {
		return;
	}

	// Remove header comment from stylesheet.
	$stylesheet_data = str_replace( get_global_stylesheet_header(), '', $stylesheet_data );

	// Add stylesheet to page head.
	echo "<style id='windmill-blocks-global-styles-inline'>" . $stylesheet_data . '</style>';
}
add_action( 'wp_head', __NAMESPACE__ . '\inline_plugin_global_styles', 100 );

/**
 * Get file path of plugin global stylesheet.
 * If stylesheet does not exist, it is first generated.
 *
 * @return string
 * @throws WP_Error - Failed to write generated stylesheet to file.
 */
function get_global_stylesheet() {
	$global_styles_cache_dir      = WINDMILL_BLOCKS_PLUGIN_DIR . 'css/';
	$global_stylesheet_basename   = 'global-styles';
	$global_stylesheet_path       = $global_styles_cache_dir . $global_stylesheet_basename . '.css';
	$global_stylesheet_asset_path = $global_styles_cache_dir . $global_stylesheet_basename . '.asset.php';

	// Create global stylesheet if it doesn't exist.
	if ( ! is_readable( $global_stylesheet_path ) ) {
		$stylesheet = generate_global_stylesheet();

		// Create style cache dir if it doesn't exist.
		if ( ! is_dir( $global_styles_cache_dir ) ) {
			if ( ! wp_mkdir_p( $global_styles_cache_dir ) ) {
				throw new WP_Error( 'Error creating global stylesheet: Failed to create stylesheet directory.' );
			}
		}

		// Write stylesheet to file.
		$stylesheet_write = file_put_contents( $global_stylesheet_path, $stylesheet['data'] );

		if ( false === $stylesheet_write ) {
			throw new WP_Error( 'Error creating global stylesheet: Failed to write stylesheet to file.' );
		}

		$asset_data  = "<?php return array('dependencies' => array(), 'version' => '" . $stylesheet['version'] . "');";
		$asset_write = file_put_contents( $global_stylesheet_asset_path, $asset_data );

		if ( false === $asset_write ) {
			throw new WP_Error( 'Error creating global stylesheet: Failed to write stylesheet asset file to file.' );
		}
	}

	return 'css/' . $global_stylesheet_basename . '.css';
}

/**
 * Get header comment for plugin global stylesheet
 */
function get_global_stylesheet_header() {
	return "/**\n * Do not edit this file directly! The contents of this file are automatically generated and will be overridden\n */\n";
}

/**
 * Generate plugin global stylesheet from theme settings and styles
 *
 * @return array
 */
function generate_global_stylesheet() {
	$global_settings = wp_get_global_settings();

	// Ensure settings were loaded.
	if ( ! is_array( $global_settings ) ) {
		return;
	}

	// Create styles array for color palette presets.
	$color_styles = generate_global_color_styles( $global_settings );

	$stylesheet = get_global_stylesheet_header() . wp_style_engine_get_stylesheet_from_css_rules(
		$color_styles,
		array(
			'context'  => null,
			'optimize' => true,
		)
	);

	return array(
		'data'         => $stylesheet,
		'dependencies' => array(),
		'version'      => bin2hex( random_bytes( 10 ) ), // Random alpha numeric version string.
	);
}

/**
 * Generate style declaration array for global color settings
 *
 * @param array $global_settings - Global settings array.
 * @return array
 */
function generate_global_color_styles( $global_settings ) {
	// Ensure settings has color settings.
	if ( ! array_key_exists( 'color', $global_settings ) ||
		! is_array( $global_settings['color'] )
	) {
		return;
	}

	$color_settings = $global_settings['color'];

	// Ensure color settings has palette settings.
	if ( ! array_key_exists( 'palette', $color_settings ) ||
		! is_array( $color_settings['palette'] )
	) {
		return;
	}

	// Create styles array for color palette presets.
	return array_reduce(
		$color_settings['palette'],
		__NAMESPACE__ . '\reduce_palette_array',
		array()
	);
}

/**
 * Global styles palette array to styles array reduce callback
 *
 * @param array $carry - Return value of previous iteration.
 * @param mixed $item - Value of current iteration.
 */
function reduce_palette_array( $carry, $item ) {
	if ( ! is_array( $item ) ) {
		return $carry;
	}

	// Create styles for palette.
	$styles = array_reduce( $item, __NAMESPACE__ . '\reduce_individual_palette_array', array() );

	return array_merge( $carry, $styles );
}

/**
 * Individual palette array to styles array reduce callback
 *
 * @param array $carry - Return value of previous iteration.
 * @param mixed $item - Value of current iteration.
 */
function reduce_individual_palette_array( $carry, $item ) {
	if ( ! is_array( $item ) || ! key_exists( 'slug', $item ) ) {
		return $carry;
	}

	// Create preset variable for preset slug.
	$preset_var = 'var(--wp--preset--color--' . $item['slug'] . ')';

	// Add preset hover color style.
	$carry[] = array(
		'selector'     => '.has-' . $item['slug'] . '-hover-color',
		'declarations' => array(
			'--wm--block--hover--color' => $preset_var,
		),
	);

	// Add preset hover background style.
	$carry[] = array(
		'selector'     => '.has-' . $item['slug'] . '-hover-background',
		'declarations' => array(
			'--wm--block--hover--background' => $preset_var,
		),
	);

	return $carry;
}
